"""init

Revision ID: 1c774e487656
Revises:
Create Date: 2025-07-14 20:39:33.846297

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1c774e487656"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
